import { Product } from './supabase';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Tênis Running Pro',
    description: 'Tênis de corrida com tecnologia de amortecimento avançada. Ideal para corridas longas e treinos intensos.',
    price: 299.99,
    stock: 15,
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    category: 'Calçados',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Camiseta Dry-Fit Performance',
    description: 'Camiseta esportiva com tecido que absorve o suor e mantém você seco durante o exercício.',
    price: 89.99,
    stock: 30,
    image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
    category: 'Roupas',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Mochila Esportiva 30L',
    description: 'Mochila resistente à água com compartimento para laptop e múltipsos bolsos organizadores.',
    price: 199.99,
    stock: 20,
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500',
    category: 'Acessórios',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Smartwatch Fitness Tracker',
    description: 'Relógio inteligente com monitoramento de frequência cardíaca, GPS e autonomia de 7 dias.',
    price: 599.99,
    stock: 10,
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
    category: 'Eletrônicos',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Garrafa Térmica 750ml',
    description: 'Garrafa em aço inoxidável que mantém bebidas quentes por 12h e frias por 24h.',
    price: 79.99,
    stock: 50,
    image_url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500',
    category: 'Acessórios',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Shorts Compressão Training',
    description: 'Shorts de compressão com tecido de alta performance para treinos de alta intensidade.',
    price: 119.99,
    stock: 25,
    image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
    category: 'Roupas',
    created_at: new Date().toISOString(),
  },
];
